// 魔法命令列表（包含消耗法力值等信息，用于 AI 提示）
module.exports = [
    { command: "/air", cost: 1, desc: "查看当前法力值" },
    { command: "/wait", cost: 10, desc: "大厅蹲人，有人进出时通知" },
    { command: "/cooling", cost: 25, desc: "获得一次性头像框" },
    { command: "/sign_", cost: 30, desc: "挂机签名" },
    { command: "/sun", cost: "未知", desc: "分享法力值给房间所有人" },
    { command: "/ring_pi", cost: 35, desc: "消息铃声变放屁声" },
    { command: "/seat_", cost: 50, desc: "换座位，可抢房主" },
    { command: "/remove_", cost: 50, desc: "拔网线，强制对方掉线" },
    { command: "/404_", cost: 50, desc: "让目标跳转到404页面" },
    { command: "/firework", cost: 30, desc: "释放烟花特效" },
    { command: "/beer_", cost: 30, desc: "酒精魔法，使对方胡言乱语" },
    { command: "/sleep_", cost: 30, desc: "催眠，使对方收不到消息" },
    { command: "/password_", cost: 100, desc: "创建/修改账号密码" },
    { command: "/timeout_", cost: "分钟数", desc: "定时掉线" },
    { command: "/english_", cost: 30, desc: "强制英语对话" },
    { command: "/recall", cost: 30, desc: "撤回上一条消息" },
    { command: "/where_", cost: 30, desc: "探测对方位置" },
    { command: "/playlist_backup", cost: 200, desc: "备份歌单" },
    { command: "/playlist_restore", cost: 200, desc: "还原歌单" },
    { command: "/copy", cost: 20, desc: "复制当前歌曲" },
    { command: "/paste", cost: 20, desc: "粘贴歌曲到当前房间" },
    { command: "/picture", cost: 30, desc: "发送自定义图片" },
    { command: "/rose_", cost: 15, desc: "送花，增加对方10法力" },
    { command: "/shoe_", cost: 15, desc: "扔拖鞋，减少对方10法力" },
    { command: "/download", cost: 30, desc: "下载当前音乐" },
    { command: "/append_", cost: "字数x20", desc: "给目标添加说话后缀" },
    { command: "/playlist_backup_file", cost: 0, desc: "歌单备份（稳定版）" },
    { command: "/playlist_restore_file", cost: 0, desc: "歌单还原（稳定版）" },
    { command: "/wow", cost: 10, desc: "释放礼炮" }
];